### ISSUE TITLE
Mailgun as a relay

### ISSUE THREAD

**Issue by N1ghteyes** [nodemailer/wildduck#143]
This is less an issue more a config question :-

Does anyone know how, or can anyone point me in the direction of how to set Wildduck to relay all sent mail through mailgun?

Thanks

**Comment by andris9** [comment]
Edit /etc/zone-mta/zones/default.toml (and possiblybounces.toml as well)

```toml
[default]
preferIPv6=false
ignoreIPv6=true
processes=1
connections=5
pool="default"
host= "smtp.mailgun.org"
port=587

[default.auth]
user="username"
pass="password"
```
