### ISSUE TITLE
Passing CMD_ARGS to a container, but wildduck still searches for db on localhost

### ISSUE THREAD

**Issue by m4rn0v** [nodemailer/wildduck#203]
I am trying to configure wildduck container as shown on the docker wiki. I am facing this error.

`wildduck_1  | ERR! Db Failed to setup database connection
wildduck_1  | {
wildduck_1  |   short_message: 'WILDDUCK [Exception] connect ECONNREFUSED 127.0.0.1:27017',
wildduck_1  |   full_message: 'MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n' +
wildduck_1  |     '    at Timeout._onTimeout (/wildduck/node_modules/mongodb/lib/core/sdam/topology.js:430:30)\n' +
wildduck_1  |     '    at listOnTimeout (internal/timers.js:549:17)\n' +
wildduck_1  |     '    at processTimers (internal/timers.js:492:7)',
wildduck_1  |   _exception: 'yes',
wildduck_1  |   _error: 'connect ECONNREFUSED 127.0.0.1:27017',
wildduck_1  |   _name: 'MongoServerSelectionError',
wildduck_1  |   facility: 'wildduck',
wildduck_1  |   host: '209.250.251.193',
wildduck_1  |   timestamp: 1588151033.613,
wildduck_1  |   _component: 'wildduck'
wildduck_1  | }
`

Which is odd because I did set CMD_ARGS in my docker-compose file and for example the host is set correctly but the db url is not and it is still pointing to localhost.

Here is my docker-compose.yml
```
version: "3"
services:
  wildduck:
    image: nodemailer/wildduck
    restart: always
    environment:
     - CMD_ARGS="--dbs.mongo=mongodb://mongo:27017/ \
       --dbs.redis=redis://redis:6379/3 \
       --smtp.setup.hostname=209.250.251.193 \
       --log.gelf.hostname=209.250.251.193 \
       --imap.setup.hostname=209.250.251.193 \
       --emailDomain=209.250.251.193"
    depends_on:
      - mongo
      - redis

  redis:
    image: redis
    restart: always
    volumes:
      - redisvol:/data

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongovol:/data/db

  debian:
    image: debian
    command: ping 8.8.8.8

volumes:
  redisvol: {}
  mongovol: {}

```
