### ISSUE TITLE
API Access Token configuration

### ISSUE THREAD

**Issue by skerit** [nodemailer/wildduck#215]
I'm trying to get DuckyPanel & DuckyAPI to work, but... it just does not. I keep getting `unauthorized` errors.

And I'm looking at the wildduck api configuration file, and I'm confused by this part:

```toml
# If set requires all API calls to have accessToken query argument with that value
# http://localhost:8080/users?accessToken=somesecretvalue
accessToken="myaccesstoken"

[accessControl]
# If true then require a valid access token to perform API calls
# If a client provides a token then it is validated even if using a token is not required
enabled=false

# Secret for HMAC
# Changing this value invalidates all tokens
secret="myhmacsecret"
```

Is just setting the `accessToken` enough, or do I need to set `enabled=true` in the `[accessControl]` section too?
