### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by AddoSolutions** [nodemailer/wildduck#71]
Hey guys, just wanted to see if there was anyone already working on a docker image for this project.  I have a pretty long history with Docker, and have dockerized a few other projects so I can certainly help significantly with this if need be.

The one really big help I have found is your install script.  It doesn't appear to be fully documented, but it only seems to work on Ubuntu Xenial flavor?  With that image, I was able to get it to install fairly well into an image, but there are several important tweaks for the install that would increase it's stability/standardize it's installation.

This is a VERY cool project, and glad that someone is FINALLY working on a replacement for the horrid file based mail systems written in a modern language.  I actually started doing it myself but ran out of time to finish (some of my progress is [here](https://github.com/AddoSolutions/unsuckish-mail) if it's of any help, though this repo is FAR more advanced).  

Let me know if I can help on this project.  I am pretty seasoned in NodeJS, MongoDB, and Docker -Redis being my weak point.

Nick

**Comment by AddoSolutions** [comment]
For anyone wanting to play with docker, you can get it about as far as I did with:
do:

```shell
# On the host
docker run --rm -it --link mongodb --link redis -p 8080:8080 -p 993:993 ubuntu:xenial bash

# In the newly created temporary container
apt-get update; \
    apt-get -y install lsof wget gnupg dnsutils curl sudo git; \
    wget https://raw.githubusercontent.com/nodemailer/wildduck/master/setup/install.sh; \
    chmod +x install.sh; \
    ./install.sh ; \
    echo 'mongo="mongodb://mongodb:27017/wildduck"
    redis="redis://redis:6379/3"' > /etc/wildduck/dbs.toml; \
    cd /opt/wildduck; \
    /usr/bin/node server.js --config="/etc/wildduck/wildduck.toml"
```

**Comment by andris9** [comment]
Actually there is nothing Ubuntu specific, for example I run the server in a custom CoreOS based system. The install script uses apt for installing the dependencies (MongoDB and such), and it uses systemd to run the services (thus the requirement for Ubuntu 16, not 14 which does not have systemd). If you manage Ubuntu and Redis separately and start the service process as a docker command then there's nothing you'd need from Ubuntu.

**Comment by AddoSolutions** [comment]
Very cool! Yeah it does a really nice Job, I’m just trying to figure out how to best dockerize it. 

From a strategic perspective is Docker something you guys are interested in formally supporting or am I going to be better off doing it separately?

**Comment by andris9** [comment]
If you are willing to maintain the docker stuff then sure, create a PR with the docker files and I'll merge.

**Comment by larstobi** [comment]
@AddoSolutions Did you make it? :-)

**Comment by AddoSolutions** [comment]
I actually didn't get to finish this project on my end.  Moving off Gmail but that is a big frog to swallow lol.

The config above should get you quite far though, you just need to make sure to add the volumes in the right place.

Something like:

```
FROM ubuntu:xenial
WORKDIR /opt/wildduck
RUN apt-get update; \
    apt-get -y install lsof wget gnupg dnsutils curl sudo git; \
    wget https://raw.githubusercontent.com/nodemailer/wildduck/master/setup/install.sh; \
    chmod +x install.sh; \
    ./install.sh ; \
    echo 'mongo="mongodb://mongodb:27017/wildduck"
    redis="redis://redis:6379/3"' > /etc/wildduck/dbs.toml
CMD /usr/bin/node server.js --config="/etc/wildduck/wildduck.toml
```

**Comment by rqelibari** [comment]
Hey there!

We have dockerized Wildduck mail server ([astzweig/wildduck](https://hub.docker.com/r/astzweig/wildduck)) and did release version [1.0.0](https://github.com/astzweig/docker-wildduck) today on GitHub. It contains a full fledged email server, but no Wildduck webmail, as we will release that in it's own docker container shortly.

## Highlights
* The container can be configured using just a few different environment variables and using the API of course. Everything else can be induced by other values. If you need more control, do not hesitate to tweak the configuration files directly (mountable).
* We developed a python program ([cocof](https://pypi.org/project/cocof/)) specifically for the
   purpose to modify YAML, TOML and JSON configuration files from CLI scripts and can therefor
   configure the system in short, concise scripts, that are far less error-prone than `sed`-based scripts.
* Most important part of our work was to actually understand how the system components relate to
  each other and map that to a good script structure.

Hope it saves you guys some time. And as always: feedback is very welcome! We sure put our best efforts into it - at least our best effort besides our day-to-day work. Enjoy :-)

**Comment by kerberjg** [comment]
@rqelibari `astzweig/wildduck` is behind on several releases of Wildduck, the docker image is still stuck on 1.1, while the latest version of Wildduck is actually 1.15

The best solution would be for Wildduck to have its own Dockerfiles in the repo, as well as autobuild configured on Docker Hub, in order for the project to be self-reliant, without the risk of a lack of updated builds which would depends entirely on external maintainers.

We're currently to integrate Wildduck as a part of our dockerized infrastructure over at @mekomidev, and we'd gladly make a pull request once everything is done on our sides and if @andris9 agrees on this.

**Comment by unixfox** [comment]
@kerberjg Based on the [Dockerfile](https://github.com/astzweig/docker-wildduck/blob/master/Dockerfile) the image is based on commit https://github.com/nodemailer/wildduck/commit/bda1cbd878e5c02dabea54886059e1fd54514054 which is the v1.15.1 of wildduck, so I don't think `astzweig/wildduck` is actually that outdated.

**Comment by andris9** [comment]
I've been really bad with changelogs (to say I haven't kept one) but comparing the latest version against astzweig/wildduck the differences in WildDuck core are mostly in filter handling:
* if a filter moves messages to a folder and that folder is deleted then the filter is deleted as well
* if there is afilter that tries to store messages to an unexisting folder then the message is stored to INBOX instead
(previous versions returned 450 error for such a message)

Additionally the authentication API endpoint was changed to return user specific access token so mail clients would be able to use user token instead of root token when making requests on behalf of the user.

So in large part the astzweig/wildduck version should work still fine.

**Comment by rqelibari** [comment]
@kerberjg Generally a good idea. Bumping the container automatically would be a nice thing, maybe through some kind of continuous integration service.

Additionally: I will prepare a new release manually today.

**Comment by manalejandro** [comment]
Something like:
```
version: "2"
services:
    wildduck:
        build: ./wildduck
        ports:
            - "25:25"
            - "465:465"
            - "993:993"
        volumes:
             - ./wildduck/config:/wildduck/config
             - ./wildduck-mta/config:/wildduck-mta/config
             - ./haraka/config:/haraka/config
        depends_on:
            - redis
            - mongo

    redis:
        image: redis:alpine
        volumes:
          - ./redis:/data
        expose:
          - 6379
    
    mongo:
        image: mongo
        volumes:
          - ./mongodb:/data/db
        expose:
          - 27017

    webmail:
        build: ./webmail
        ports:
          - "3000:3000"
        volumes:
          - ./webmail/config:/webmail/config
        depends_on:
          - redis
          - mongo
          - wildduck

```

:+1:
